#!/usr/bin/env bash
# ──────────────────────────────────────────────
# RouteIQ — One-line installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/osippay/routeiq/main/install.sh | bash
#
# What it does:
#   1. Clones the repo to ~/.routeiq
#   2. Creates a Python virtual environment
#   3. Installs dependencies
#   4. Creates .env from template
#   5. Adds 'routeiq' command to PATH
#
# Run again to update.
# ──────────────────────────────────────────────

set -euo pipefail

INSTALL_DIR="${ROUTEIQ_HOME:-$HOME/.routeiq}"
REPO_URL="https://github.com/osippay/routeiq.git"
BRANCH="main"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[RouteIQ]${NC} $1"; }
ok()    { echo -e "${GREEN}[RouteIQ]${NC} $1"; }
warn()  { echo -e "${YELLOW}[RouteIQ]${NC} $1"; }
error() { echo -e "${RED}[RouteIQ]${NC} $1" >&2; }

# ── Preflight checks ──

command -v python3 >/dev/null 2>&1 || {
    error "Python 3 is required but not found."
    error "Install it: https://www.python.org/downloads/"
    exit 1
}

PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
PYTHON_MAJOR=$(echo "$PYTHON_VERSION" | cut -d. -f1)
PYTHON_MINOR=$(echo "$PYTHON_VERSION" | cut -d. -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 10 ]); then
    error "Python 3.10+ is required. Found: Python $PYTHON_VERSION"
    exit 1
fi

command -v git >/dev/null 2>&1 || {
    error "git is required but not found."
    exit 1
}

# ── Clone or update ──

if [ -d "$INSTALL_DIR/.git" ]; then
    info "Updating existing installation in $INSTALL_DIR..."
    cd "$INSTALL_DIR"
    git fetch origin "$BRANCH" --quiet
    git reset --hard "origin/$BRANCH" --quiet
    ok "Updated to latest version."
else
    info "Installing RouteIQ to $INSTALL_DIR..."
    git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR" --quiet
    ok "Repository cloned."
fi

cd "$INSTALL_DIR"

# ── Virtual environment ──

if [ ! -d "venv" ]; then
    info "Creating virtual environment..."
    python3 -m venv venv
    ok "Virtual environment created."
fi

info "Installing dependencies..."
venv/bin/pip install --quiet --upgrade pip
venv/bin/pip install --quiet -e .
ok "Dependencies installed."

# ── .env file ──

if [ ! -f ".env" ]; then
    if [ -f ".env.example" ]; then
        cp .env.example .env
        warn "Created .env from template. Edit it to add your API keys:"
        warn "  $INSTALL_DIR/.env"
    fi
else
    ok ".env file already exists."
fi

# ── State directory ──

mkdir -p state

# ── Create launcher script ──

LAUNCHER="/usr/local/bin/routeiq"
LAUNCHER_ALT="$HOME/.local/bin/routeiq"

create_launcher() {
    local target="$1"
    cat > "$target" << SCRIPT
#!/usr/bin/env bash
# RouteIQ launcher — auto-generated by install.sh
cd "$INSTALL_DIR"
exec venv/bin/python cli.py "\$@"
SCRIPT
    chmod +x "$target"
}

# Try system-wide first, fall back to user-local
if [ -w "$(dirname "$LAUNCHER")" ] 2>/dev/null; then
    create_launcher "$LAUNCHER"
    ok "Command installed: routeiq (system-wide)"
elif command -v sudo >/dev/null 2>&1; then
    sudo bash -c "$(declare -f create_launcher); create_launcher '$LAUNCHER'"
    ok "Command installed: routeiq (system-wide via sudo)"
else
    mkdir -p "$(dirname "$LAUNCHER_ALT")"
    create_launcher "$LAUNCHER_ALT"
    ok "Command installed: $LAUNCHER_ALT"

    # Check if ~/.local/bin is in PATH
    if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
        warn "Add this to your shell profile (~/.bashrc or ~/.zshrc):"
        warn "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    fi
fi

# ── Done ──

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         RouteIQ installed successfully!      ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo "  Quick start:"
echo ""
echo "    1. Add your API key:"
echo "       ${CYAN}nano $INSTALL_DIR/.env${NC}"
echo ""
echo "    2. Test it:"
echo "       ${CYAN}routeiq \"write a fibonacci function\"${NC}"
echo ""
echo "    3. Start the proxy:"
echo "       ${CYAN}routeiq serve${NC}"
echo ""
echo "    4. Check discovered credentials:"
echo "       ${CYAN}routeiq credentials${NC}"
echo ""
echo "  Docs:  https://github.com/osippay/routeiq"
echo "  Config: $INSTALL_DIR/conf/router.yaml"
echo ""

# ── Optional: install embeddings classifier ──

echo -n "Install ML classifier (sentence-transformers, ~80MB)? [y/N] "
read -r -t 10 answer || answer="n"
if [[ "$answer" =~ ^[Yy]$ ]]; then
    info "Installing sentence-transformers..."
    venv/bin/pip install --quiet "sentence-transformers>=2.2.0"
    ok "ML classifier installed. RouteIQ will use embeddings for classification."
else
    ok "Skipped. Using keyword classifier (no extra dependencies)."
fi

echo ""
ok "Done! Run 'routeiq --help' to get started."
